- hosts: nodes
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
    - name: Creates /etc/docker
      file:
        path: /etc/docker
        state: directory 
    - name: Start Docker service
      service:
        name: docker
        daemon_reload: yes
        state: started
        enabled: yes
